"""
ProtocolHandler interface.

Abstract interface for HotStuff protocol variants.
"""

from abc import ABC
from abc import abstractmethod
from typing import List

from hotstuff.domain.types.view_number import ViewNumber
from hotstuff.domain.models.replica_state import ReplicaState
from hotstuff.domain.models.messages.base_message import BaseMessage


class ProtocolHandler(ABC):
    """
    Abstract interface for protocol implementations.
    
    Implementations provide the core consensus logic.
    Both Basic HotStuff and Chained HotStuff implement this interface.
    """
    
    @abstractmethod
    def handle_message(self, message: BaseMessage, current_time: int) -> List:
        """
        Handle an incoming message.
        
        Args:
            message: The message to process.
            current_time: Current simulation time.
            
        Returns:
            List of events generated by handling this message.
        """
        pass
    
    @abstractmethod
    def start_view(self, view_number: ViewNumber, current_time: int) -> List:
        """
        Start a new view.
        
        Args:
            view_number: The new view number.
            current_time: Current simulation time.
            
        Returns:
            List of events generated by starting this view.
        """
        pass
    
    @abstractmethod
    def on_timeout(self, current_time: int) -> List:
        """
        Handle a timeout event.
        
        Args:
            current_time: Current simulation time.
            
        Returns:
            List of events generated by the timeout.
        """
        pass
    
    @abstractmethod
    def get_state(self) -> ReplicaState:
        """
        Get the current state of the protocol handler.
        
        Returns:
            ReplicaState snapshot.
        """
        pass
